import { Controller, Get, Post, Put, Body, Param, Query, Req, UseGuards } from '@nestjs/common';
import { ApiTags, ApiOperation, ApiBearerAuth } from '@nestjs/swagger';
import { Request } from 'express';
import { AttendanceService } from './attendance.service';
import { PayrollService } from './payroll.service';
import { UpsertSalaryStructureDto } from './dto/upsert-salary-structure.dto';
import { RunPayrollDto } from './dto/run-payroll.dto';
import { JwtAuthGuard } from '../../common/guards/jwt-auth.guard';
import { PermissionsGuard } from '../../common/guards/permissions.guard';
import { RequirePermissions } from '../../common/decorators/require-permissions.decorator';

@ApiTags('Human Resources — Attendance & Payroll')
@ApiBearerAuth()
@UseGuards(JwtAuthGuard, PermissionsGuard)
@Controller('api/v1/hr')
export class HrController {
  constructor(
    private readonly attendanceService: AttendanceService,
    private readonly payrollService: PayrollService,
  ) {}

  @Post('attendance/clock-in')
  @ApiOperation({ summary: 'Record a check-in for the authenticated employee, today' })
  async clockIn(@Req() req: Request) {
    return this.attendanceService.clockIn(req.context!);
  }

  @Post('attendance/clock-out')
  @ApiOperation({ summary: 'Record a check-out for the authenticated employee, today' })
  async clockOut(@Req() req: Request) {
    return this.attendanceService.clockOut(req.context!);
  }

  @Get('attendance/me')
  @ApiOperation({ summary: "Get the authenticated employee's attendance register for a period" })
  async getMyAttendance(@Req() req: Request, @Query('year') year?: string, @Query('month') month?: string) {
    const now = new Date();
    return this.attendanceService.getMyAttendance(
      req.context!,
      year ? Number(year) : now.getFullYear(),
      month ? Number(month) : now.getMonth() + 1,
    );
  }

  @Get('attendance/:personId')
  @ApiOperation({ summary: "Get an employee's attendance register for a period (HR/manager view)" })
  @RequirePermissions('hr.attendance.read')
  async getEmployeeAttendance(
    @Param('personId') personId: string,
    @Req() req: Request,
    @Query('year') year?: string,
    @Query('month') month?: string,
  ) {
    const now = new Date();
    return this.attendanceService.getAttendanceForEmployee(
      req.context!,
      personId,
      year ? Number(year) : now.getFullYear(),
      month ? Number(month) : now.getMonth() + 1,
    );
  }

  @Get('payroll/salary-structure/me')
  @ApiOperation({ summary: "Get the authenticated employee's own salary structure" })
  async getMySalaryStructure(@Req() req: Request) {
    return this.payrollService.getMySalaryStructure(req.context!);
  }

  @Get('payroll/salary-structure/:personId')
  @ApiOperation({ summary: "Get an employee's salary structure (HR/Finance view)" })
  @RequirePermissions('hr.payroll.read')
  async getSalaryStructure(@Param('personId') personId: string) {
    return this.payrollService.getSalaryStructure(personId);
  }

  @Put('payroll/salary-structure/:personId')
  @ApiOperation({ summary: "Create or update an employee's salary structure" })
  @RequirePermissions('hr.payroll.manage')
  async upsertSalaryStructure(
    @Param('personId') personId: string,
    @Body() dto: UpsertSalaryStructureDto,
    @Req() req: Request,
  ) {
    return this.payrollService.upsertSalaryStructure(personId, dto, req.context!);
  }

  @Get('payroll/payslips/me')
  @ApiOperation({ summary: "Get the authenticated employee's own payslip history" })
  async getMyPayslips(@Req() req: Request) {
    return this.payrollService.getMyPayslips(req.context!);
  }

  @Post('payroll/runs')
  @ApiOperation({ summary: 'Generate payroll (payslips) for every employee in a company for a period' })
  @RequirePermissions('hr.payroll.manage')
  async runPayroll(@Body() dto: RunPayrollDto, @Req() req: Request) {
    return this.payrollService.runPayroll(dto, req.context!);
  }

  @Post('payroll/runs/:id/finalize')
  @ApiOperation({ summary: 'Finalize a payroll run — posts the GL journal entry and marks payslips paid' })
  @RequirePermissions('hr.payroll.manage')
  async finalizePayrollRun(@Param('id') id: string, @Req() req: Request) {
    return this.payrollService.finalizePayrollRun(id, req.context!);
  }

  @Get('payroll/runs')
  @ApiOperation({ summary: "List payroll runs within the caller's organizational scope" })
  @RequirePermissions('hr.payroll.read')
  async getPayrollRuns(@Req() req: Request) {
    return this.payrollService.getPayrollRuns(req.context!);
  }

  @Get('payroll/runs/:id/payslips')
  @ApiOperation({ summary: 'List payslips generated by a specific payroll run' })
  @RequirePermissions('hr.payroll.read')
  async getPayslipsForRun(@Param('id') id: string, @Req() req: Request) {
    return this.payrollService.getPayslipsForRun(id, req.context!);
  }
}
